// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpRGyO8GqsCrBguOUHmF1w77kb7Qq3YpY',
    appId: '1:78467174289:web:3d3f7954d73b8fdc1e9430',
    messagingSenderId: '78467174289',
    projectId: 'fruitebuyer',
    authDomain: 'fruitebuyer.firebaseapp.com',
    databaseURL: 'https://fruitebuyer-default-rtdb.firebaseio.com',
    storageBucket: 'fruitebuyer.appspot.com',
    measurementId: 'G-24NTWM8DDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC6hiIomFbRMmZ4RNdmA5xP6JN5aOYs4A',
    appId: '1:78467174289:android:e3298266f9fbb0981e9430',
    messagingSenderId: '78467174289',
    projectId: 'fruitebuyer',
    databaseURL: 'https://fruitebuyer-default-rtdb.firebaseio.com',
    storageBucket: 'fruitebuyer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWITXC-W6NtvJ-6xqdVXzNvpBoRN08Qeo',
    appId: '1:78467174289:ios:b718c3254cc249421e9430',
    messagingSenderId: '78467174289',
    projectId: 'fruitebuyer',
    databaseURL: 'https://fruitebuyer-default-rtdb.firebaseio.com',
    storageBucket: 'fruitebuyer.appspot.com',
    iosBundleId: 'com.example.vendorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWITXC-W6NtvJ-6xqdVXzNvpBoRN08Qeo',
    appId: '1:78467174289:ios:b718c3254cc249421e9430',
    messagingSenderId: '78467174289',
    projectId: 'fruitebuyer',
    databaseURL: 'https://fruitebuyer-default-rtdb.firebaseio.com',
    storageBucket: 'fruitebuyer.appspot.com',
    iosBundleId: 'com.example.vendorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpRGyO8GqsCrBguOUHmF1w77kb7Qq3YpY',
    appId: '1:78467174289:web:3d3f7954d73b8fdc1e9430',
    messagingSenderId: '78467174289',
    projectId: 'fruitebuyer',
    authDomain: 'fruitebuyer.firebaseapp.com',
    databaseURL: 'https://fruitebuyer-default-rtdb.firebaseio.com',
    storageBucket: 'fruitebuyer.appspot.com',
    measurementId: 'G-24NTWM8DDE',
  );

}